Repository jpmorganchase/salt-ds, pull requests merged in 2022-09, with the labels that each got.

#374 Tweaks on border storybook examples
  .changeset/kind-news-help.md
  packages/core/src/__tests__/__e2e__/layout/Border.cy.tsx
  packages/core/src/layout/BorderLayout/BorderLayout.css
  packages/core/stories/layout/border-item.stories.tsx
  packages/core/stories/layout/border-layout.doc.stories.mdx
  packages/core/stories/layout/border-layout.stories.tsx
  packages/core/stories/layout/flow-layout.stories.tsx
  packages/core/stories/layout/styles.css
Labels: Design: Review Done, Content: Review Done

#292 Update layer layout and carousel storybook examples, remove border from layer and add animations to layer layout
  .changeset/plenty-cows-train.md
  packages/lab/src/__tests__/__e2e__/layout/Layer.cy.tsx
  packages/lab/src/layout/LayerLayout/LayerLayout.css
  packages/lab/src/layout/LayerLayout/LayerLayout.tsx
  packages/lab/stories/carousel.stories.css
  packages/lab/stories/carousel.stories.tsx
  packages/lab/stories/layout/layer-layout.stories.tsx
  packages/lab/stories/layout/styles.css
Labels: Design: Signed Off, Content: Signed Off

#351 Update ToolkitProvider docs
  packages/core/stories/toolkit-provider.doc.stories.mdx
Labels: documentation
