Repository jpmorganchase/salt-ds, pull requests merged in 2024-03, with the labels that each got.

#3055 Vertical navigation to site
  site/docs/components/navigation-item/usage.mdx
  site/docs/patterns/index.mdx
  site/docs/patterns/navigation.mdx
  site/docs/patterns/vertical-navigation.mdx
  site/public/img/patterns/vertical-navigation/anatomy.png
  site/public/img/patterns/vertical-navigation/application-layout.png
  site/public/img/patterns/vertical-navigation/blur-active-nested.png
  site/public/img/patterns/vertical-navigation/blur-active.png
  site/public/img/patterns/vertical-navigation/group-multi-level.png
  site/public/img/patterns/vertical-navigation/group-single-level.png
  site/public/img/patterns/vertical-navigation/responsive-narrow.png
  site/public/img/patterns/vertical-navigation/responsive-wide.png
  site/public/img/patterns/vertical-navigation/secondary-navigation.png
  site/public/img/patterns/vertical-navigation/spacing.png
  site/public/img/patterns/vertical-navigation/within-modals.png
Labels: role: design 🎨, role: content 📝

#3041 Fix Tab deletion during editing
  .changeset/witty-flies-bake.md
  packages/lab/src/tabs/Tab.tsx
Labels: CLA: Received, community

#3120 Make request for feedback on foundation pages consistent
  site/docs/foundations/accent.mdx
  site/docs/foundations/color.mdx
  site/docs/foundations/density.mdx
  site/docs/foundations/division.mdx
  site/docs/foundations/duration.mdx
  site/docs/foundations/fragments/feedback.mdx
  site/docs/foundations/iconography.mdx
  site/docs/foundations/modes.mdx
  site/docs/foundations/opacity.mdx
  site/docs/foundations/responsiveness.mdx
  site/docs/foundations/scale.mdx
  site/docs/foundations/shadow.mdx
  site/docs/foundations/size.mdx
  site/docs/foundations/spacing.mdx
  site/docs/foundations/typography.mdx
Labels: role: content 📝

#3073 Selectable card pattern to site
  site/docs/patterns/index.mdx
  site/docs/patterns/selectable-card.mdx
  site/public/img/patterns/selectable-card/anatomy.png
  site/public/img/patterns/selectable-card/grid-no-spacing.png
  site/public/img/patterns/selectable-card/grid-spacing.png
  site/public/img/patterns/selectable-card/layout-spacing.png
  site/public/img/patterns/selectable-card/multiple.png
  site/public/img/patterns/selectable-card/selectable-card.png
  site/public/img/patterns/selectable-card/single-no-radio.png
  site/public/img/patterns/selectable-card/single-radio.png
  site/public/img/patterns/selectable-card/stack-no-spacing.png
  site/public/img/patterns/selectable-card/stack-spacing.png
  site/public/sitemap.xml
Labels: role: design 🎨, role: content 📝

#3139 List builder pattern to site
  site/docs/patterns/list-builder.mdx
  site/public/img/patterns/list-builder/anatomy.png
  site/public/img/patterns/list-builder/empty-state.png
  site/public/img/patterns/list-builder/filter-and-sort.png
  site/public/img/patterns/list-builder/image.png
  site/public/img/patterns/list-builder/layout.png
  site/public/img/patterns/list-builder/multi-select.png
  site/public/img/patterns/list-builder/non-reorderable.png
  site/public/img/patterns/list-builder/single-select.png
  site/public/img/patterns/list-builder/stack-layout.png
Labels: role: design 🎨, role: content 📝

#3141 List filtering to site
  site/docs/patterns/index.mdx
  site/docs/patterns/list-builder.mdx
  site/docs/patterns/list-filtering.mdx
  site/public/img/patterns/list-filtering/list-filter-logic.png
  site/public/img/patterns/list-filtering/list-filter-no-matches.png
  site/public/img/patterns/list-filtering/list-filter-slow-loading.png
  site/public/img/patterns/list-filtering/list-filter.png
  site/public/img/patterns/list-filtering/list-filtering-combobox.png
Labels: role: design 🎨, role: content 📝
